spring.application.name=medical-clinic
spring.mvc.problemdetails.enabled=true
spring.datasource.url=jdbc:postgresql://localhost:5432/medical_clinic
spring.datasource.username=postgres
spring.datasource.password=228007
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
info.app.name=Medical Clinic API
info.app.description=REST API for managing patients, doctors and visits
info.app.version=0.0.1-SNAPSHOT
info.app.java-version=21
